// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-b8aQpqOrPOPtrsbiJ_NHQenSmZbkDaE',
    appId: '1:1086978762239:web:ba7d2df8799b2f8d9b33ca',
    messagingSenderId: '1086978762239',
    projectId: 'dtaraang-chek',
    authDomain: 'dtaraang-chek.firebaseapp.com',
    storageBucket: 'dtaraang-chek.firebasestorage.app',
    measurementId: 'G-RLJP095WXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28eIJdmnN_5td6QeLDYzZ_n8LJD6oEEM',
    appId: '1:1086978762239:android:d36d46ed145d3c2f9b33ca',
    messagingSenderId: '1086978762239',
    projectId: 'dtaraang-chek',
    storageBucket: 'dtaraang-chek.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ruXVo7yjnE4FCCZptIbPfdxQFz_FTfA',
    appId: '1:1086978762239:ios:9bdc60c26d9b2c7c9b33ca',
    messagingSenderId: '1086978762239',
    projectId: 'dtaraang-chek',
    storageBucket: 'dtaraang-chek.firebasestorage.app',
    iosBundleId: 'com.example.dtaraangChek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ruXVo7yjnE4FCCZptIbPfdxQFz_FTfA',
    appId: '1:1086978762239:ios:9bdc60c26d9b2c7c9b33ca',
    messagingSenderId: '1086978762239',
    projectId: 'dtaraang-chek',
    storageBucket: 'dtaraang-chek.firebasestorage.app',
    iosBundleId: 'com.example.dtaraangChek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-b8aQpqOrPOPtrsbiJ_NHQenSmZbkDaE',
    appId: '1:1086978762239:web:3c0a111d0f0999dd9b33ca',
    messagingSenderId: '1086978762239',
    projectId: 'dtaraang-chek',
    authDomain: 'dtaraang-chek.firebaseapp.com',
    storageBucket: 'dtaraang-chek.firebasestorage.app',
    measurementId: 'G-K4J1V8LZNM',
  );
}
